-- Regula ID-uri: BD_AM = impare (1,3,5...), BD_EU = pare (2,4,6...)

-- BD_AM
-- Permiterea insert-ului manual pentru coloanele IDENTITY
ALTER TABLE REZERVARE_AM MODIFY (id_rezervare GENERATED BY DEFAULT ON NULL AS IDENTITY);
ALTER TABLE PLATA_AM MODIFY (id_plata GENERATED BY DEFAULT ON NULL AS IDENTITY);
ALTER TABLE BILET_AM MODIFY (id_bilet GENERATED BY DEFAULT ON NULL AS IDENTITY);

-- A. Tabele Replicate (Nomenclatoare și Zboruri)
INSERT INTO TARA SELECT * FROM BLUEHORIZON.TARA;
INSERT INTO ORAS SELECT * FROM BLUEHORIZON.ORAS;
INSERT INTO AEROPORT SELECT * FROM BLUEHORIZON.AEROPORT;
INSERT INTO AVION SELECT * FROM BLUEHORIZON.AVION;
INSERT INTO ZBOR SELECT * FROM BLUEHORIZON.ZBOR;

-- B. Tabela Centralizată (Date unice globale)
INSERT INTO PASAGER SELECT * FROM BLUEHORIZON.PASAGER;

-- C. Fragmente Verticale (Utilizator)
-- Partea de securitate (Centralizată pe AM)
INSERT INTO UTILIZATOR_SEC (id_user, email, parola, rol)
SELECT id_user, email, parola, rol FROM BLUEHORIZON.UTILIZATOR;

-- Partea de profil (Replicată pe AM)
INSERT INTO UTILIZATOR_DATA (id_user, nume, prenume, telefon, data_inregistrare)
SELECT id_user, nume, prenume, telefon, data_inregistrare FROM BLUEHORIZON.UTILIZATOR;

-- D. Fragmente Orizontale (Tranzacții POS America)
-- POS = Point of Sale (America/Europa)
INSERT INTO REZERVARE_AM (id_rezervare, id_user, data_rezervare, regiune_vanzare, total_de_plata, status)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 - 1 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'AM'
)
SELECT m.new_id, r.id_user, r.data_rezervare, r.regiune_vanzare, r.total_de_plata, r.status
FROM BLUEHORIZON.REZERVARE r JOIN rez_map m ON r.id_rezervare = m.old_id;

-- Plati America (id-uri impare)
INSERT INTO PLATA_AM (id_plata, id_rezervare, suma_achitata, data_plata, metoda_plata, status)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 - 1 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'AM'
)
SELECT ROW_NUMBER() OVER (ORDER BY p.id_plata) * 2 - 1,
       m.new_id, p.suma_achitata, p.data_plata, p.metoda_plata, p.status
FROM BLUEHORIZON.PLATA p JOIN rez_map m ON p.id_rezervare = m.old_id;

-- Bilete America (id-uri impare)
INSERT INTO BILET_AM (id_bilet, id_rezervare, id_zbor, id_pasager, numar_rand, litera_scaun, clasa, pret_final)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 - 1 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'AM'
)
SELECT ROW_NUMBER() OVER (ORDER BY b.id_bilet) * 2 - 1,
       m.new_id, b.id_zbor, b.id_pasager, b.numar_rand, b.litera_scaun, b.clasa, b.pret_final
FROM BLUEHORIZON.BILET b JOIN rez_map m ON b.id_rezervare = m.old_id;

COMMIT;

-- Resincronizam secventele IDENTITY pentru AM
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(id_rezervare), -1) INTO v_max FROM REZERVARE_AM;
    EXECUTE IMMEDIATE 'ALTER TABLE REZERVARE_AM MODIFY (id_rezervare GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
    SELECT NVL(MAX(id_plata), -1) INTO v_max FROM PLATA_AM;
    EXECUTE IMMEDIATE 'ALTER TABLE PLATA_AM MODIFY (id_plata GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
    SELECT NVL(MAX(id_bilet), -1) INTO v_max FROM BILET_AM;
    EXECUTE IMMEDIATE 'ALTER TABLE BILET_AM MODIFY (id_bilet GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
END;
/


-- BD_EU
-- Permiterea insert-ului manual pentru coloanele IDENTITY
ALTER TABLE REZERVARE_EU MODIFY (id_rezervare GENERATED BY DEFAULT ON NULL AS IDENTITY);
ALTER TABLE PLATA_EU MODIFY (id_plata GENERATED BY DEFAULT ON NULL AS IDENTITY);
ALTER TABLE BILET_EU MODIFY (id_bilet GENERATED BY DEFAULT ON NULL AS IDENTITY);

-- A. Tabele Replicate (Nomenclatoare și Zboruri)
INSERT INTO TARA SELECT * FROM BLUEHORIZON.TARA;
INSERT INTO ORAS SELECT * FROM BLUEHORIZON.ORAS;
INSERT INTO AEROPORT SELECT * FROM BLUEHORIZON.AEROPORT;
INSERT INTO AVION SELECT * FROM BLUEHORIZON.AVION;
INSERT INTO ZBOR SELECT * FROM BLUEHORIZON.ZBOR;

-- B. Fragment Vertical Replicat (Utilizator Data)
INSERT INTO UTILIZATOR_DATA (id_user, nume, prenume, telefon, data_inregistrare)
SELECT id_user, nume, prenume, telefon, data_inregistrare FROM BLUEHORIZON.UTILIZATOR;

-- C. Fragmente Orizontale (Tranzacții POS Europa)
INSERT INTO REZERVARE_EU (id_rezervare, id_user, data_rezervare, regiune_vanzare, total_de_plata, status)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'EU'
)
SELECT m.new_id, r.id_user, r.data_rezervare, r.regiune_vanzare, r.total_de_plata, r.status
FROM BLUEHORIZON.REZERVARE r JOIN rez_map m ON r.id_rezervare = m.old_id;

-- Plati Europa (id-uri pare)
INSERT INTO PLATA_EU (id_plata, id_rezervare, suma_achitata, data_plata, metoda_plata, status)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'EU'
)
SELECT ROW_NUMBER() OVER (ORDER BY p.id_plata) * 2,
       m.new_id, p.suma_achitata, p.data_plata, p.metoda_plata, p.status
FROM BLUEHORIZON.PLATA p JOIN rez_map m ON p.id_rezervare = m.old_id;

-- Bilete Europa (id-uri pare)
INSERT INTO BILET_EU (id_bilet, id_rezervare, id_zbor, id_pasager, numar_rand, litera_scaun, clasa, pret_final)
WITH rez_map AS (
    SELECT id_rezervare AS old_id,
           ROW_NUMBER() OVER (ORDER BY id_rezervare) * 2 AS new_id
    FROM BLUEHORIZON.REZERVARE WHERE regiune_vanzare = 'EU'
)
SELECT ROW_NUMBER() OVER (ORDER BY b.id_bilet) * 2,
       m.new_id, b.id_zbor, b.id_pasager, b.numar_rand, b.litera_scaun, b.clasa, b.pret_final
FROM BLUEHORIZON.BILET b JOIN rez_map m ON b.id_rezervare = m.old_id;

COMMIT;

-- Resincronizam secventele IDENTITY pentru EU
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(id_rezervare), 0) INTO v_max FROM REZERVARE_EU;
    EXECUTE IMMEDIATE 'ALTER TABLE REZERVARE_EU MODIFY (id_rezervare GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
    SELECT NVL(MAX(id_plata), 0) INTO v_max FROM PLATA_EU;
    EXECUTE IMMEDIATE 'ALTER TABLE PLATA_EU MODIFY (id_plata GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
    SELECT NVL(MAX(id_bilet), 0) INTO v_max FROM BILET_EU;
    EXECUTE IMMEDIATE 'ALTER TABLE BILET_EU MODIFY (id_bilet GENERATED ALWAYS AS IDENTITY (START WITH ' || (v_max + 2) || ' INCREMENT BY 2))';
END;
/
