-- CREATE USER
CREATE USER bluehorizon_dw IDENTIFIED BY parola_dw
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO bluehorizon_dw;
GRANT CREATE TABLE TO bluehorizon_dw;
GRANT CREATE VIEW TO bluehorizon_dw;
GRANT CREATE SEQUENCE TO bluehorizon_dw;
GRANT CREATE MATERIALIZED VIEW TO bluehorizon_dw;

GRANT SELECT ON UTILIZATOR TO bluehorizon_dw;
GRANT SELECT ON PASAGER TO bluehorizon_dw;
GRANT SELECT ON TARA TO bluehorizon_dw;
GRANT SELECT ON ORAS TO bluehorizon_dw;
GRANT SELECT ON AEROPORT TO bluehorizon_dw;
GRANT SELECT ON AVION TO bluehorizon_dw;
GRANT SELECT ON ZBOR TO bluehorizon_dw;
GRANT SELECT ON REZERVARE TO bluehorizon_dw;
GRANT SELECT ON PLATA TO bluehorizon_dw;
GRANT SELECT ON BILET TO bluehorizon_dw;

-- CREATE TABLES
-- DIMENSIUNEA TIMP
CREATE TABLE DIM_TIMP (
    id_dim_timp NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_timp PRIMARY KEY,
    data_calendaristica DATE NOT NULL
         CONSTRAINT uk_dim_timp_data UNIQUE DISABLE VALIDATE, -- verifica datele existente, nu face index (pt a economisi spatiul), dar blocheaza orice insert (devine read-only)
                                                            -- in viitorul proces etl va trebui sa alteram coloana cu DISABLE NOVALIDATE,
                                                            -- apoi vor fi inserate datele si vom resigila coloana printr-un alt alter pe coloana cu DISABLE VALIDATE
    an NUMBER(4) NOT NULL,
    trimestru NUMBER(1) NOT NULL,
    nume_luna VARCHAR2(20),
    luna NUMBER(2) NOT NULL,
    nume_zi VARCHAR2(20),
    zi NUMBER(2) NOT NULL,
    CONSTRAINT chk_dim_timp_trimestru CHECK (trimestru BETWEEN 1 AND 4),
    CONSTRAINT chk_dim_timp_luna CHECK (luna BETWEEN 1 AND 12),
    CONSTRAINT chk_dim_timp_zi CHECK (zi BETWEEN 1 AND 31)
);

-- DIMENSIUNEA AEROPORT
CREATE TABLE DIM_AEROPORT (
    id_dim_aeroport NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_aeroport PRIMARY KEY,
    id_aeroport_oltp NUMBER(10) NOT NULL
         CONSTRAINT uk_dim_aeroport_oltp UNIQUE DISABLE VALIDATE,
    cod_iata CHAR(3) NOT NULL
         CONSTRAINT uk_dim_aeroport_iata UNIQUE DISABLE VALIDATE,
    nume_aeroport VARCHAR2(200) NOT NULL,
    oras VARCHAR2(100) NOT NULL,
    tara VARCHAR2(100) NOT NULL
);

-- DIMENSIUNEA AVION
CREATE TABLE DIM_AVION (
    id_dim_avion NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_avion PRIMARY KEY,
    id_avion_oltp NUMBER(10) NOT NULL
         CONSTRAINT uk_dim_avion_oltp UNIQUE DISABLE VALIDATE,
    numar_inmatriculare VARCHAR2(20) NOT NULL
         CONSTRAINT uk_dim_avion_nr UNIQUE DISABLE VALIDATE,
    model VARCHAR2(100) NOT NULL,
    capacitate NUMBER(5) NOT NULL,
    an_fabricatie NUMBER(4),
    CONSTRAINT chk_dim_avion_capacitate CHECK (capacitate > 0)
);

-- DIMENSIUNEA CLASA
CREATE TABLE DIM_CLASA (
    id_dim_clasa NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_clasa PRIMARY KEY,
    nume_clasa VARCHAR2(50) NOT NULL
         CONSTRAINT uk_dim_clasa_nume UNIQUE DISABLE VALIDATE
);

INSERT INTO DIM_CLASA (nume_clasa) VALUES ('ECONOMY');
INSERT INTO DIM_CLASA (nume_clasa) VALUES ('BUSINESS');
COMMIT;

-- DIMENSIUNEA PASAGER
CREATE TABLE DIM_PASAGER (
    id_dim_pasager NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_pasager PRIMARY KEY,
    id_pasager_oltp NUMBER(10) NOT NULL
         CONSTRAINT uk_dim_pasager_oltp UNIQUE DISABLE VALIDATE,
    nationalitate VARCHAR2(3),
    varsta NUMBER(3),
    grupa_varsta VARCHAR2(20),
    CONSTRAINT chk_dim_pasager_varsta CHECK (varsta BETWEEN 0 AND 120)
);

-- DIMENSIUNEA UTILIZATOR
CREATE TABLE DIM_UTILIZATOR (
    id_dim_utilizator NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
         CONSTRAINT pk_dim_utilizator PRIMARY KEY,
    id_user_oltp NUMBER(10) NOT NULL
         CONSTRAINT uk_dim_utilizator_oltp UNIQUE DISABLE VALIDATE,
    vechime_cont_ani NUMBER(3)
);

-- TABEL FACT - FACT_VANZARI
CREATE TABLE FACT_VANZARI (
    id_vanzare NUMBER(15) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    
    id_dim_timp_rezervare NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_timp_rez
         REFERENCES DIM_TIMP(id_dim_timp)
         RELY DISABLE NOVALIDATE, -- nu verifica corectitudinea datelor la insert (am facut asta deja in etl), nu verifica nici datele existente, "promitem" ca sunt corecte (pentru optimizare)
    id_dim_timp_plecare NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_timp_plec
         REFERENCES DIM_TIMP(id_dim_timp)
         RELY DISABLE NOVALIDATE,
    id_dim_aeroport_plecare NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_aero_plec
         REFERENCES DIM_AEROPORT(id_dim_aeroport)
         RELY DISABLE NOVALIDATE,
    id_dim_aeroport_sosire NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_aero_sos
         REFERENCES DIM_AEROPORT(id_dim_aeroport)
         RELY DISABLE NOVALIDATE,
    id_dim_avion NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_avion
         REFERENCES DIM_AVION(id_dim_avion)
         RELY DISABLE NOVALIDATE,
    id_dim_pasager NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_pasager
         REFERENCES DIM_PASAGER(id_dim_pasager)
         RELY DISABLE NOVALIDATE,
    id_dim_clasa NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_clasa
         REFERENCES DIM_CLASA(id_dim_clasa)
         RELY DISABLE NOVALIDATE,
    id_dim_utilizator NUMBER(10) NOT NULL
         CONSTRAINT fk_fact_utilizator
         REFERENCES DIM_UTILIZATOR(id_dim_utilizator)
         RELY DISABLE NOVALIDATE,
         
    data_plecare_part DATE NOT NULL,
    pret_bilet NUMBER(10,2) NOT NULL,
    durata_zbor NUMBER(8,2),
    minute_intarziere NUMBER(8,2) DEFAULT 0,
    status_zbor VARCHAR2(20),
    
    CONSTRAINT pk_fact_vanzari PRIMARY KEY (id_vanzare),
    CONSTRAINT chk_fact_pret CHECK (pret_bilet >= 0),
    CONSTRAINT chk_fact_durata CHECK (durata_zbor >= 0),
    CONSTRAINT chk_fact_status CHECK (status_zbor IN ('PROGRAMAT','ANULAT','INTARZIAT','IMBARCAT','IN_ZBOR','ATERIZAT'))
)
PARTITION BY RANGE (data_plecare_part) (
    PARTITION p_2023 VALUES LESS THAN (DATE '2024-01-01'),
    PARTITION p_2024 VALUES LESS THAN (DATE '2025-01-01'),
    PARTITION p_2025 VALUES LESS THAN (DATE '2026-01-01'),
    PARTITION p_future VALUES LESS THAN (MAXVALUE)
);

-- BITMAP
CREATE BITMAP INDEX bidx_fact_timp_rez ON FACT_VANZARI(id_dim_timp_rezervare) LOCAL;
CREATE BITMAP INDEX bidx_fact_timp_plec ON FACT_VANZARI(id_dim_timp_plecare) LOCAL;
CREATE BITMAP INDEX bidx_fact_aero_plec ON FACT_VANZARI(id_dim_aeroport_plecare) LOCAL;
CREATE BITMAP INDEX bidx_fact_aero_sos ON FACT_VANZARI(id_dim_aeroport_sosire) LOCAL;
CREATE BITMAP INDEX bidx_fact_avion ON FACT_VANZARI(id_dim_avion) LOCAL;
CREATE BITMAP INDEX bidx_fact_pasager ON FACT_VANZARI(id_dim_pasager) LOCAL;
CREATE BITMAP INDEX bidx_fact_clasa ON FACT_VANZARI(id_dim_clasa) LOCAL;
CREATE BITMAP INDEX bidx_fact_utilizator ON FACT_VANZARI(id_dim_utilizator) LOCAL;
CREATE BITMAP INDEX bidx_fact_status ON FACT_VANZARI(status_zbor) LOCAL;

-- B-TREE (Normali)
CREATE INDEX idx_fact_data_part ON FACT_VANZARI(data_plecare_part) LOCAL;

CREATE INDEX idx_dim_timp_an_luna ON DIM_TIMP(an, luna);
CREATE INDEX idx_dim_timp_trim ON DIM_TIMP(an, trimestru);

CREATE INDEX idx_dim_aero_iata ON DIM_AEROPORT(cod_iata);
CREATE INDEX idx_dim_aero_oras ON DIM_AEROPORT(oras);
CREATE INDEX idx_dim_aero_tara ON DIM_AEROPORT(tara);

CREATE INDEX idx_dim_avion_nr ON DIM_AVION(numar_inmatriculare);

CREATE INDEX idx_dim_pasager_grupa ON DIM_PASAGER(grupa_varsta);
CREATE INDEX idx_dim_pasager_nat ON DIM_PASAGER(nationalitate);

CREATE INDEX idx_utilizator_vech ON DIM_UTILIZATOR(vechime_cont_ani);

COMMIT;
